# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.
"""


import pandas as pd

import csv


recipe = pd.read_csv("recipe.csv")
recipe.head()

import pandas as pd
df_tomorrow = pd.read_csv('veg-price-analysis/veg_pred.csv')
df_tomorrow = df_tomorrow[df_tomorrow["產品名稱"] != "其他"]
df_tomorrow

from datetime import datetime, timedelta
import pandas as pd

# 讀取 CSV
df_price = pd.read_csv("veg-price-analysis/veg_prices_history.csv")
df_price['交易日期'] = pd.to_datetime(df_price['交易日期']).dt.date

# 篩選最近一個月
today = datetime.today().date()
one_month_ago = today - timedelta(days=30)
df_recent = df_price[df_price['交易日期'] >= one_month_ago]
df_recent = df_recent[~df_recent["產品名稱"].str.contains("其他")]


print(f"最近一個月資料筆數: {df_recent.shape[0]}")
df_recent

# 先清理產品名稱（去空格，必要時取第一個詞）
df_recent['產品名稱'] = df_recent['產品名稱'].str.strip().str.split().str[0]

# 用 groupby 切分
grouped = df_recent.groupby('產品名稱')

# 儲存成變數 t1, t2, ...（方便後續使用）
for i, (name, group) in enumerate(grouped, start=1):
    globals()[f't{i}'] = group
    print(f"產品名稱: {name} 儲存為變數 t{i}，筆數: {len(group)}")

avg_price_dict = {}

for i in range(1, len(grouped)+1):
    df_veg = globals()[f't{i}']
    avg_price_dict[df_veg['產品名稱'].iloc[0]] = df_veg['加權平均價(元/公斤)'].mean()

print(avg_price_dict)

import pandas as pd
from datetime import datetime, timedelta

# === 讀取菜價資料，假設已經算出 avg_price_dict 字典 ===
tomorrow_price = dict(zip(df_tomorrow['產品名稱'], df_tomorrow['預測明日菜價(元/公斤)']))

# === 讀取食譜資料 ===
df_recipe = pd.read_csv("recipe.csv")  # 格式: 菜名,主要食材(用|分隔),輔助食材(用|分隔)

# === 互動程式 ===
print("哈囉~我來給你建議吧")
print('輸入「明日菜價」→ 輸出前五名便宜蔬菜及明日預測價格')
print('輸入「建議食譜」→ 直接提供可煮的菜色及食材')

def handle_user_message(user_input):
   user_input = input("\n請輸入指令：").strip()

   if user_input == "明日菜價":
     # 計算前五名蔬菜
     diffs = []
     for veg, avg in avg_price_dict.items():
        if veg in tomorrow_price:
          diffs.append((veg, avg, tomorrow_price[veg]))

     # 先找低於平均的蔬菜
     under_avg = [x for x in diffs if x[2] < x[1]]
     if len(under_avg) >= 5:
       selected = sorted(under_avg, key=lambda x: x[1]-x[2], reverse=True)[:5]
     else:
     # 如果不足五個，取離平均最近的前五個
       selected = sorted(diffs, key=lambda x: abs(x[1]-x[2]))[:5]

     result = "前五名蔬菜及明日價格：\n"
     for veg, avg, price in selected:
        result += f"{veg} → {price:.2f} 元/公斤\n"

   elif user_input == "建議食譜":
      if df_recipe.empty:
         return "抱歉，食譜資料中沒有資料 😢"

      # 取得前五個蔬菜名稱
      top5_veggies = [veg for veg, _, _ in selected]
      for veggie in top5_veggies:
         veggie_lower = veggie.lower().strip()
         # 篩選主要食材列表中包含該蔬菜
         recipes_for_veggie = df_recipe[
            df_recipe["主要食材"].str.split("、").apply(lambda x: veggie in x)
              ]
         if recipes_for_veggie.empty:
            result += f"{veggie} → 沒有對應食譜 😢\n"
         else:
            result += f"{veggie} 的食譜：\n"
            for _, row in recipes_for_veggie.iterrows():
              result += f"- {row['菜名']} → 需要食材: {row['主要食材']} + {row['輔助食材']}\n"
      return result
   else:
      return result

"""#分詞 以防有人多打"""

# 檢視資料
#df.head(10)

# import jieba

# def cutProcess(sting):
#     result = jieba.lcut(sting)
#     result = " ".join(result)

#     return result

# df['quote'] = df['quote'].apply(cutProcess)

# df.head(5)

"""#訓練資料"""

# data = df
# training_documents = data['quote'].values.astype('U')
# labels = data['category'].values.astype('U')

# #切分训练集和测试集，分为80%训练集，20%测试集
# X_train, X_test, y_train, y_test = train_test_split(training_documents, labels, test_size=0.1, random_state=12)


# vectorizer = CountVectorizer(token_pattern='(?u)\\b\\w+\\b') # token_pattern='(?u)\\b\\w+\\b' 單字也計入
# x_train = vectorizer.fit_transform(X_train)

# # train
# classifier = MultinomialNB (alpha=0.01) # change model type here
# classifier.fit(x_train, y_train)

# training_documents

# for i in x_train:
#     print("#:"i)

"""#評估模型

"""

# x_test = vectorizer.transform(X_test)
# classifier.score(x_test,y_test)

# print(X_test)
# predict(X_test)

# def predict(raw_queries,n_top=1):
#     raw_queries = [cutProcess(s) for s in raw_queries]
# #     print(raw_queries)

#     queries = vectorizer.transform(raw_queries)
#     predict =  classifier.predict_proba(queries).tolist()
#     predict = [{k:round(v,4) for k,v in zip(classifier.classes_[:3],qa[:3])} for qa in predict]
#     predict = [ sorted(dictt.items(), key=lambda d: d[1], reverse=True) for dictt in predict]
#     return predict

# example = ['我有問題','修改公司資料','我想在台中市東山路附近找小雞上工上的工作','要怎麼變更公司電話','您好應徵者為何看不到我們需要出差的項目']

# lists = predict(example)

# for index,qa in enumerate(lists):
#     print("question:",example[index])
#     print("anser:", qa)

#     print()

# txt = input()
# predict([txt])[0]

